// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientFontWrapper from "../components/ClientFontWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Use stable fallback className during SSR */}
      <body className="antialiased">
        {/* Apply dynamic font variables client-side */}
        <ClientFontWrapper>{children}</ClientFontWrapper>
      </body>
    </html>
  );
}


